###`Q-1:` Find the nearest element in the array to a given integer.
```
Ex:-
a=23 and array - [10 17 24 31 38 45 52 59].
Nearest element is 24
```
Hint: Read about this function `argmin()`

In [4]:
import numpy as np
a=np.array([10, 17, 24, 31 ,38, 45 ,52, 59])
print(np.argmin(a=23))

0


###`Q-2:` Replace multiples of 3 or 5 as 0 in the given array.
```
arr=[1 2 3 4 5 6 7 9]

result-> [1 2 0 4 0 0 7 0]
```

In [9]:
a=np.array([1, 2, 3, 4, 5, 6, 7, 9])
a[(a%3==0 ) | (a%5==0)] = 0
print(a)

[1 2 0 4 0 0 7 0]


###`Q-3:` Use Fancy Indexing.
1. Double the array elements at  given indexes
```
arr = np.arrange(10)
indexes = [0,3,4,9]
```
Result -> `[ 0  1  2  6  8  5  6  7  8 18]`

2. Using a given array make a different array as in below example
```
array = [1,2,3]
result array -> [1 1 1 2 2 2 3 3 3]
```
* Internal-repetion should be as length of the array.

Hint:
```
if a is an array
a = [2,4]
a[[1,1,0,1]] will result in-> [4 4 2 4]
```

In [13]:
# Part 2: Repeat each element in arr as many times as the length of arr
arr=np.arange(10)
result = np.repeat(arr[:3], len(arr[:3]))
print(result)

[0 0 0 1 1 1 2 2 2]


In [12]:
arr=np.arange(10)
indicies=[0,3,4,9]
a=arr[indicies]*2
print(a)

[ 0  6  8 18]


###`Q-4:` Your are given an array which is havig some nan value. You job is to fill those nan values with most common element in the array.
```
arr=np.array([[1,2,np.nan],[4,2,6],[np.nan,np.nan,5]])

```

In [14]:
from collections import Counter

arr = np.array([[1, 2, np.nan], [4, 2, 6], [np.nan, np.nan, 5]])

# Flatten and remove nan values
flat = arr.flatten()
non_nan = flat[~np.isnan(flat)]

# Find the most common element
most_common = Counter(non_nan).most_common(1)[0][0]

# Fill nan values with the most common element
filled_arr = np.where(np.isnan(arr), most_common, arr)
print(filled_arr)

[[1. 2. 2.]
 [4. 2. 6.]
 [2. 2. 5.]]


### `Q-5:` Write a NumPy program

- to find the missing data in a given array. Return a boolean matrix.
- also try to fill those missing values with 0. For that, you can use `np.nan_to_num(a)`

```python
import numpy as np

np.array([[3, 2, np.nan, 1],
          [10, 12, 10, 9],
          [5, np.nan, 1, np.nan]])
```

In [ ]:
# code here

###`Q-6:` Given two arrays, X and Y, construct the Cauchy matrix C.
`Cij =1/(xi - yj)`

http://en.wikipedia.org/wiki/Cauchy_matrix
```
x = numpy.array([1,2,3,4]).reshape((-1, 1)
y = numpy.array([5,6,7])
```

In [ ]:
# code here

###`Q-7:` Plot this below equation.

$$\large y = \frac{e^x - e^{-x}}{e^x + e^{-x}}$$

**Note: This equation is called tanh activation function. In deep learning, many times this function is used. If you find some difference between the sigmoid function and this tanh function, note that to your notebook.**

In [15]:
def tenh(array):
    return (np.exp(array)-np.exp(-array))/(np.exp(array)+np.exp(-array))
print(tenh(np.array([0,1,2,3,4,5,6,7,8,9])) )

[0.         0.76159416 0.96402758 0.99505475 0.9993293  0.9999092
 0.99998771 0.99999834 0.99999977 0.99999997]


### `Q-8:` Plot the below equation.

$$\large y = \sqrt{36 - (x - 4)^2} + 2$$

The range of x should be between -2 to 10. $x ∈ [-2, 10]$



In [18]:
def equate_y(x,y):
    if (x>-2 and x<10):
        return (np.sqrt(36-np.square(x-4))+2)
    else:
        return "Doesnt satisfy condition"
print(equate_y(2,5))

7.656854249492381


### `Q-9:` Write a program implement Boradcasting Rule to check if two array can be added or not.
Given tuples of shapes.
```
shape of a- (3,2,2)
shape of b- (2,2)

check_broadcast(a, b) -> return Boolean (True if can broadcasted, False other wise.)
```

In [19]:
def check_Broadcast(a,b):
    try:
        np.broadcast(a,b)
        return True
    except ValueError:
        return False

In [21]:
check_Broadcast((3,2,2), (2,2))

False