**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [2]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [6]:
a=np.zeros(10)
a[5:6]=1
a

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [10]:
a=input("Enter A")
b=input("Enter B")
array = np.random.random((int(a), int(b)))
print(array)
print(np.average(array))

[[0.79623129 0.882337   0.68085756 0.02763395 0.52192566]
 [0.58473587 0.47354687 0.88204305 0.07028689 0.08726306]
 [0.79990453 0.10562667 0.73771286 0.26512645 0.64212186]
 [0.31262067 0.64247637 0.04900209 0.11072441 0.36679984]
 [0.08021705 0.95134241 0.76564965 0.0179953  0.03527068]]
0.43557808263449266


###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [13]:
array=np.ones((4,4))
array[1:3,1:3]=0
array

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [21]:
vec = np.linspace(0, 1, 12)[1:-1]
print(vec)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [ ]:
#NO 
# np.identity(3).reshape(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [28]:
np.linspace(0,5,25).reshape(5,5)

array([[0.        , 0.20833333, 0.41666667, 0.625     , 0.83333333],
       [1.04166667, 1.25      , 1.45833333, 1.66666667, 1.875     ],
       [2.08333333, 2.29166667, 2.5       , 2.70833333, 2.91666667],
       [3.125     , 3.33333333, 3.54166667, 3.75      , 3.95833333],
       [4.16666667, 4.375     , 4.58333333, 4.79166667, 5.        ]])

###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [34]:
array=np.linspace(1,100,20).reshape(10,2)
np.astype(array,int)


array([[  1,   6],
       [ 11,  16],
       [ 21,  27],
       [ 32,  37],
       [ 42,  47],
       [ 53,  58],
       [ 63,  68],
       [ 73,  79],
       [ 84,  89],
       [ 94, 100]])

###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [38]:
array=np.random.random(336).reshape(6,7,8)
indicies=np.unravel_index(99,(6,7,8))
print(indicies)

(np.int64(1), np.int64(5), np.int64(3))


### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [44]:
array=np.array((1,2,3,4,-8,-10))
result=np.astype(array,float)
result[::-1]

array([-10.,  -8.,   4.,   3.,   2.,   1.])

### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [49]:
a=eval(input("Enter A:"))
print(len(np.array(a)))

7


### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [54]:
a=[33.17344305, 45.61961654 ,82.05405781 ,80.9647098  ,68.82830233 ,91.52064278]
a1=np.array(a)
print(a1**a1)

[2.81746590e+050 4.89622270e+075 1.14730062e+157 3.19604372e+154
 3.09304799e+126 3.30738953e+179]


### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [59]:
a=np.arange(0,10).reshape(2,5)
b=np.ones((2,5))
c=np.random.random((2,5))
d=np.vstack((a,b,c))
print(d)

[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.74911093 0.91965794 0.34418102 0.02022977 0.25179072]
 [0.86564726 0.88431248 0.88007134 0.14534064 0.08183874]]


### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [60]:
from datetime import datetime, timedelta
import numpy as np

def date_array(start, end):
    # Check if inputs are strings
    if not isinstance(start, str) or not isinstance(end, str):
        raise TypeError("Both inputs must be strings")
    
    try:
        # Convert string dates to datetime objects
        start_date = datetime.strptime(start, '%Y-%m-%d')
        end_date = datetime.strptime(end, '%Y-%m-%d')
        
        # Check if dates are in same year
        if start_date.year != end_date.year:
            raise ValueError("Dates must be from the same year")
        
        # Check if start date is before end date
        if start_date > end_date:
            raise ValueError("Start date must be before end date")
        
        # Calculate number of days between dates (inclusive)
        delta = (end_date - start_date).days + 1
        
        # Generate array of dates
        dates = [start_date + timedelta(days=i) for i in range(delta)]
        
        # Convert to string format YYYY-MM-DD
        date_strings = np.array([date.strftime('%Y-%m-%d') for date in dates])
        
        return date_strings
    
    except ValueError as e:
        if "does not match format" in str(e):
            raise ValueError("Date format must be YYYY-MM-DD")
        else:
            raise e

###`Q-14:` Subtract the mean of each row from a matrix.

In [67]:
array1=np.random.random(10).reshape(2,5)
a=array1-np.mean(array1,axis=1,keepdims=True)
a

array([[-0.26242692,  0.41413593,  0.22212197, -0.35897147, -0.01485951],
       [-0.37072512,  0.02302115,  0.42159889, -0.23418729,  0.16029238]])

###`Q-15:` Swap column-1 of array with column-2 in the array.

In [7]:
a1=np.arange(10).reshape(2,5)
a2=np.arange(10,20).reshape(2,5)
# Swap column-1 with column-2 in a1
a1_swapped = a1.copy()
a1_swapped[:, [0, 1]] = a1_swapped[:, [1, 0]]
print(a1_swapped)

# Swap column-1 with column-2 in a2
a2_swapped = a2.copy()
a2_swapped[:, [0, 1]] = a2_swapped[:, [1, 0]]
print(a2_swapped)

[[1 0 2 3 4]
 [6 5 7 8 9]]
[[11 10 12 13 14]
 [16 15 17 18 19]]


###`Q-16:` Replace odd elements in arrays with -1.

In [14]:
array = np.random.random(10).reshape(2,5)
print(array)
# Replace odd elements with -1
array[array % 2 != 0] = -1
print(array)
    

[[0.03201427 0.10266319 0.19550694 0.33705637 0.19359266]
 [0.32546041 0.24807675 0.56413743 0.79760177 0.59022411]]
[[-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]]


###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [23]:
result = np.maximum(a, b)
print(result)

[6 3 1 7 8]


In [25]:
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

array=np.vstack((a,b))
print(np.maximum(a,b))
    

[6 3 1 7 8]


###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [27]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[2003, 3227, 6315, 6320, 2487],
       [1167, 1642, 8732, 5101, 7427],
       [8949, 1436, 6554, 3952, 3645],
       [5054, 9927, 7608, 4652, 3274],
       [2639, 9201, 6550, 8597, 6094],
       [7169, 1609, 6970, 6362, 5054],
       [1123, 8852, 1100, 2248, 6173],
       [9087, 2230,  525, 2193, 4870]], dtype=int32)

In [33]:
array=np.array(arr1[::,::2])
array
result=arr1-np.min(arr1,axis=1,keepdims=True)/(np.max(arr1,axis=1,keepdims=True)-np.min(arr1,axis=1,keepdims=True))
result

array([[2002.53602038, 3226.53602038, 6314.53602038, 6319.53602038,
        2486.53602038],
       [1166.84573695, 1641.84573695, 8731.84573695, 5100.84573695,
        7426.84573695],
       [8948.80886463, 1435.80886463, 6553.80886463, 3951.80886463,
        3644.80886463],
       [5053.50789118, 9926.50789118, 7607.50789118, 4651.50789118,
        3273.50789118],
       [2638.59783603, 9200.59783603, 6549.59783603, 8596.59783603,
        6093.59783603],
       [7168.71061151, 1608.71061151, 6969.71061151, 6361.71061151,
        5053.71061151],
       [1122.85810114, 8851.85810114, 1099.85810114, 2247.85810114,
        6172.85810114],
       [9086.93868255, 2229.93868255,  524.93868255, 2192.93868255,
        4869.93868255]])

###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [34]:
a = eval(input("Enter A:"))
array = np.array(a)
b = int(input("Enter B:"))
if b <= len(a):
    # nth largest: sort descending and pick (b-1)th
    sorted_array = np.sort(array)[::-1]
    print(sorted_array[b-1])
else:
    print("B must be less than or equal to the length of the array.")

12


###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [40]:
pattern = np.concatenate([np.repeat(a, 3), np.tile(a, 5)])
print(pattern)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3]


In [39]:
a=np.array([1,2,3])
print(a*3)

[3 6 9]
